// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knypuamkpsryemwpgndl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueXB1YW1rcHNyeWVtd3BnbmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzA1NTAsImV4cCI6MjA1OTE0NjU1MH0.weq8z-41GZqWwYW7y5zJekNkfRe3OZHBabpR1Aan8Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);